# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mimir < Formula
  desc "Language-agnostic code indexer using tree-sitter and SQLite"
  homepage "https://github.com/Utahjezz/mimir"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Utahjezz/mimir/releases/download/v0.2.1/mimir_0.2.1_darwin_amd64.tar.gz"
      sha256 "b27269a0e2a354c1d37d307978c148a72d495b0dbbdcd7ca98f4b728a44833bf"

      define_method(:install) do
        bin.install "mimir"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Utahjezz/mimir/releases/download/v0.2.1/mimir_0.2.1_darwin_arm64.tar.gz"
      sha256 "f45747e02e5f7d38deabf7777172925bb8431e557cd95e922edd8bdd344ede59"

      define_method(:install) do
        bin.install "mimir"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Utahjezz/mimir/releases/download/v0.2.1/mimir_0.2.1_linux_amd64.tar.gz"
      sha256 "f8fcce40ebadafde61fc77179c255dfa534e0237c132a0e6f44704dc288d7a2c"
      define_method(:install) do
        bin.install "mimir"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Utahjezz/mimir/releases/download/v0.2.1/mimir_0.2.1_linux_arm64.tar.gz"
      sha256 "183897ace43d84562f349ca7cf4a6715bcf60ebaed1d12020dde88d44d498910"
      define_method(:install) do
        bin.install "mimir"
      end
    end
  end

  test do
    system "#{bin}/mimir", "--version"
  end
end
