# This file was generated by GoReleaser. DO NOT EDIT.
cask "mimir" do
  name "mimir"
  desc "Language-agnostic code indexer using tree-sitter and SQLite"
  homepage "https://github.com/Utahjezz/mimir"
  version "0.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mimir"

  on_macos do
    on_intel do
      url "https://github.com/Utahjezz/mimir/releases/download/v#{version}/mimir_#{version}_darwin_amd64.tar.gz"
      sha256 "5d8a7ce1eb48717f5481604f2ef5fb051b727b5ac1113cd21f3173ce83fc8624"
    end
    on_arm do
      url "https://github.com/Utahjezz/mimir/releases/download/v#{version}/mimir_#{version}_darwin_arm64.tar.gz"
      sha256 "fcf3cf7149df3dfc888a755e067d4f93da2794b3f4f6c87272ad78f65e895bf3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Utahjezz/mimir/releases/download/v#{version}/mimir_#{version}_linux_amd64.tar.gz"
      sha256 "791658ab6cd89679afa5a5f01a80bf9e24b1afeb42d41437a938de2aafd43181"
    end
    on_arm do
      url "https://github.com/Utahjezz/mimir/releases/download/v#{version}/mimir_#{version}_linux_arm64.tar.gz"
      sha256 "b6ee500d292b01e95fd4979d7e9ad4882cf70a286bc776da9fa9ecfe6e6f5389"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mimir"]
    end
  end

  # No zap stanza required
end
